### ISSUE TITLE
Good addon

### ISSUE THREAD

**Issue by Geniusssmit** [lovac42/Wordsworth#4]
Can I ask you to add option to use several frequency lists at the same time?

**Comment by lovac42** [comment]
You could just merge these lists into one. But I suppose I could allow you to add more files of the same type, appending them one after the other. Then the data in the previous files would take priority over the later files.

**Comment by Geniusssmit** [comment]
Idea is:
I have several freq list for Japanese:
netflix
books
VNs
anime.
Basically I want 4 fields in anki, 1 for for each one of those.
If I can somehow do that, pls tell me.

**Comment by lovac42** [comment]
I'm afraid the current structure isn't designed for that. Multifields aren't supported and each one needs to be checked for proper formatting to avoid corruption. So you would need to do each field separately, close and do another field.

**Comment by Geniusssmit** [comment]
And I also have to change frequency list every time, right?

**Comment by lovac42** [comment]
Actually, you don't need to close, just change the list after each one, so long as you are operating on the same batch of notes. If you want different notes, then you would need to close.

I thought about adding a job manager, but these operations take less then 2-10 seconds, so it's not really worth it, unless you have a slow machine like a surface?
